### PR TITLE
Add support for heating messages

### PR DESCRIPTION
**Pull request by johanek**
Needed to rename some things to make them less electric specific - i.e. results for channels

Will produce output for heating like:
('192.168.1.208', 22600): <OwlMessage: rssi=-64, lqi=49, battery=2990mV, results=<OwlTemperature: zone=0, current=18.87, required=19.0>>

### CODE REVIEW

**Comment by micolous** [comment]
Thanks!

Todo for me to look at later (or you!)
- update `rrd.py` so it handles the new API format
- implement temperature monitors in `rrd.py` as well
- then merge

**Comment by johanek** [comment]
Documentation for owl multicast: https://theowl.zendesk.com/hc/en-gb/articles/201284603-Multicast-UDP-API-Information

**Comment by johanek** [comment]
Hey - I've taken your code and cut it down to something simple so I can push the data to graphite.

I know what I've shared with you needs work, and I'm sorry but I can't see myself having any time to work on this :disappointed:

**Comment by micolous** [comment]
Thanks.

I've refactored this a fair bit and pushed it up.  It splits the `electricity` and `heating` message types properly and notes the silly differences in the protocol between them.

You may also be interested in looking at `rrd.py` -- it logs electricity usage information using RRDtool's Python API, and demonstrates how to inherit from a Twisted protocol object.

**Comment by johanek** [comment]
Nice work. Thanks for the help this has been with getting my home monitoring data collection working.

**Pull request merged**
